name: Deploy using Docker Compose

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup SSH
              uses: webfacetory/ssh-agent@v0.7.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Copy project files to server
              run: | 
               rsync -avz --exclude ".git" ./ ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}}:/app/trade_management_system/

            - name: Deploy with Docker Compose
              run: | 
                ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP}} "
                    cd /app/trade_management_system &&
                    docker compose pull && 
                    docker compose down &&
                    docker compose up -d --build
                "